# Generated by Django 2.1.15 on 2020-05-02 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_design_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='like_users',
            field=models.ManyToManyField(related_name='like_design', to=settings.AUTH_USER_MODEL),
        ),
    ]
