# Generated by Django 2.1.15 on 2020-06-07 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_design_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=100)),
                ('fake', models.BooleanField()),
                ('have_user', models.ManyToManyField(related_name='have_artwork', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
