# Generated by Django 2.1.15 on 2020-06-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='fossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
                ('bell', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fossil_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tmi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_title', models.CharField(max_length=100)),
                ('jp_title', models.CharField(max_length=100)),
                ('en_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fossil',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.fossil_category'),
        ),
        migrations.AddField(
            model_name='fossil',
            name='have_user',
            field=models.ManyToManyField(related_name='have_fossil', to=settings.AUTH_USER_MODEL),
        ),
    ]
