# Generated by Django 3.0.7 on 2020-07-02 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_auto_20200607_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='have_user',
            field=models.ManyToManyField(related_name='have_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
