# Generated by Django 2.1.15 on 2020-05-02 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('where', models.TextField()),
                ('bell', models.IntegerField()),
                ('catch_user', models.ManyToManyField(related_name='catch_bug', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('where', models.TextField()),
                ('size', models.TextField()),
                ('bell', models.IntegerField()),
                ('catch_user', models.ManyToManyField(related_name='catch_fish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Villagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_name', models.CharField(max_length=10)),
                ('jp_name', models.CharField(max_length=10)),
                ('en_name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.TextField()),
                ('character', models.TextField()),
                ('species', models.CharField(max_length=10)),
                ('like_user', models.ManyToManyField(related_name='like_villager', to=settings.AUTH_USER_MODEL)),
                ('live_with', models.ManyToManyField(related_name='live_villager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
