# Generated by Django 2.1.15 on 2020-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bug_fish_villagers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
